config/routes.rb
RestaurantReview::Application.routes.draw do
  resources :reviews

  resources :restaurants

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :location, :name, :telephone

  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :rating, :restaurant_id, :user_id, :text

  validates_presence_of :user, :restaurant, :rating, :text

  belongs_to :restaurant
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  has_many :reviews
  has_many :restaraunts, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]  

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
    @restaurant = @review.restaurant
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])
    @restaurant = @review.restaurant

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review.restaurant, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.haml
%h2 Welcome to Restaurant Reviews!

%h3
  =link_to "Browse By Restaurant", restaurants_path

%h3
  =link_to "Browse By User", users_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Restaurantreview", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Restaurantreview"
      %meta{:content => content_for?(:description) ? yield(:description) : "Restaurantreview", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/restaurants/_form.html.haml
= form_for @restaurant do |f|
  - if @restaurant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@restaurant.errors.count, "error")} prohibited this restaurant from being saved:"
      %ul
        - @restaurant.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :telephone
    = f.text_field :telephone
  .actions
    = f.submit 'Save'

app/views/restaurants/edit.html.haml
%h1 Editing restaurant

= render 'form'

= link_to 'Show', @restaurant
\|
= link_to 'Back', restaurants_path

app/views/restaurants/index.html.haml
%h1 Listing restaurants

%table
  %tr
    %th Name
    %th Location
    %th Telephone
    %th Number of reviews
    %th Average

  - @restaurants.each do |restaurant|
    %tr
      %td= link_to restaurant.name, restaurant 
      %td= restaurant.location
      %td= restaurant.telephone
      %td= restaurant.reviews.count
      %td= restaurant.reviews.average(:rating)
      - if current_user
        %td
          - if restaurant.reviews.where(user_id: current_user.id).count == 1
            Modify
          -else
            = link_to "Review it!", new_review_path(restaurant_id: restaurant.id)

%br

- if current_user
  = link_to "Don't see what you're looking for?  Add a new restaurant!", new_restaurant_path

app/views/restaurants/new.html.haml
%h1 New restaurant

= render 'form'

= link_to 'Back', restaurants_path

app/views/restaurants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @restaurant.name
%p
  %b Location:
  = @restaurant.location
%p
  %b Telephone:
  = @restaurant.telephone

- @reviews.each do |review|
  %h4 
    Review by 
    = review.user.name
  .rating
    Rating:
    = review.rating 
  .text
    Review
    = review.text

- if current_user
  - if @restaurant.reviews.where(user_id: current_user.id)
    mod
  -else
    = link_to 'Rate it', new_review_path(restaurant_id: @restaurant.id)

%div
  = link_to 'Back', restaurants_path

app/views/reviews/_form.html.haml
= form_for @review do |f|
  - if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :restaurant_id, value: @restaurant.id

  .field
    = f.label :rating
    - 5.times do |i|
      = i+1
      = f.radio_button :rating, i+1

  .field 
    = f.label :review
    = f.text_field :text
  .actions
    = f.submit 'Save'

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Show', @review
\|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
%h1 Listing reviews

%table
  %tr
    %th User
    %th Restaurant
    %th Rating
    %th
    %th
    %th

  - @reviews.each do |review|
    %tr
      %td= review.user_id
      %td= review.restaurant_id
      %td= review.rating
      %td= link_to 'Show', review
      %td= link_to 'Edit', edit_review_path(review)
      %td= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Review', new_review_path

app/views/reviews/new.html.haml
%h1 
  New review

= render 'form'

= link_to 'Back', reviews_path

app/views/reviews/show.html.haml
%p#notice= notice

%p
  %b User:
  = @review.user_id
%p
  %b Restaurant:
  = @review.restaurant_id
%p
  %b Rating:
  = @review.rating

= link_to 'Edit', edit_review_path(@review)
\|
= link_to 'Back', reviews_path

app/views/users/index.html.haml
%h3 Users
%table
  %tr
    %th Name
    %th Number of Reviews
  - @users.each do |user|
    %tr
      %td= link_to user.name, user
      %td= user.reviews.count

app/views/users/show.html.haml
%h3
  Reviews by
  = @user.name

- @user.reviews.each do |review|
  .review
    %h4= link_to review.restaurant.name, restaurant_path(review.restaurant.id)
    .rating
      Rating: 
      = review.rating
    .text
      = review.text